services:
  chippy-pwa:
    image: ghcr.io/DesNZ/buildertools:latest
    container_name: chippy-pwa
    ports:
      - "7090:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
